# Docker Compose configuration for Anchor Insight AI
# Provides easy development and production deployment

version: '3.8'

services:
  anchor-insight-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anchor-insight-ai
    ports:
      - "7003:7003"
    environment:
      # Override default settings for containerized environment
      - APP_ENV=production
      - HOST=0.0.0.0
      - PORT=7003
      # Camera settings for container
      - CAMERA_INDEX=0
      - CAMERA_WIDTH=640
      - CAMERA_HEIGHT=480
      # Performance settings
      - DETECTION_INTERVAL_SECONDS=1.0
      - CONFIDENCE_THRESHOLD=0.5
    volumes:
      # Mount .env file for local configuration
      - ./.env:/app/.env:ro
      # Optional: Mount source code for development (uncomment for dev mode)
      # - ./src:/app/src
    restart: unless-stopped
    networks:
      - anchor-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:7003/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  anchor-network:
    driver: bridge

# Optional: For development with live reload
# To enable development mode:
# 1. Uncomment the volumes section above
# 2. Change environment to development
# 3. Run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
