# Development override for Docker Compose
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  anchor-insight-ai:
    environment:
      - ENVIRONMENT=development
    volumes:
      # Mount source code for live reload during development
      - ./src:/app/src
      - ./.env:/app/.env
    command: ["python", "-m", "src.main_refactored"]
    # Enable live reload by mounting the source
    depends_on: []
